services:
  db-1:
    image: "postgres:17-alpine"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "db1"
      POSTGRES_USER: "db1"
      POSTGRES_DB: "db1"

  db-2:
    image: "postgres:17-alpine"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "db2"
      POSTGRES_USER: "db2"
      POSTGRES_DB: "db2"

  db-3:
    image: "postgres:17-alpine"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: "db3"
      POSTGRES_USER: "db3"
      POSTGRES_DB: "db3"
